services:
  mysql:
    image: bitnami/mariadb:10.6
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      MARIADB_DATABASE: ${DB_NAME:-dataease}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD:-nu4x599Wq7u0Bn8EABh3J91G}
    healthcheck:
      test: "mysql -h127.0.0.1 -uroot -p$$MARIADB_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  dataease:
    image: steedos/dataease:${VERSION:-latest}
    build: .
    restart: always
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME:-dataease}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-nu4x599Wq7u0Bn8EABh3J91G}
    ports:
      - ${HTTP_PORT:-8100}:8100
    healthcheck:
      test: "check http://localhost:8100"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    depends_on:
      mysql:
        condition: service_healthy